// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package importer

import (
	"context"
	"github.com/google/wire"
	"sgf-meetup-api/pkg/shared/clock"
	"sgf-meetup-api/pkg/shared/db"
	"sgf-meetup-api/pkg/shared/httpclient"
	"sgf-meetup-api/pkg/shared/logging"
)

// Injectors from wire.go:

func InitService(ctx context.Context, config *Config) (*Service, error) {
	serviceConfig := NewServiceConfig(config)
	timeSource := clock.RealTimeSource()
	loggingConfig := getLoggingConfig(config)
	logger := logging.DefaultLogger(loggingConfig)
	eventDBRepositoryConfig := NewEventDBRepositoryConfig(config)
	dbConfig := getDbConfig(config)
	client, err := db.New(ctx, dbConfig, logger)
	if err != nil {
		return nil, err
	}
	importerEventDBRepository := NewEventDBRepository(eventDBRepositoryConfig, client, timeSource, logger)
	meetupProxyGraphQLHandlerConfig := NewMeetupProxyGraphQLHandlerConfig(config)
	graphQLHandler := NewMeetupProxyGraphQLHandler(meetupProxyGraphQLHandlerConfig, logger)
	importerMeetupRepository := NewMeetupRepository(graphQLHandler, logger)
	service := NewService(serviceConfig, timeSource, logger, importerEventDBRepository, importerMeetupRepository)
	return service, nil
}

// wire.go:

var CommonSet = wire.NewSet(logging.DefaultLogger, clock.RealTimeSource, httpclient.DefaultClient, getLoggingConfig)

var DBSet = wire.NewSet(getDbConfig, db.New)
