// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package importer

import (
	"context"
	"github.com/google/wire"
	"sgf-meetup-api/pkg/importer/importerconfig"
	"sgf-meetup-api/pkg/shared/appconfig"
	"sgf-meetup-api/pkg/shared/clock"
	"sgf-meetup-api/pkg/shared/db"
	"sgf-meetup-api/pkg/shared/httpclient"
	"sgf-meetup-api/pkg/shared/logging"
)

// Injectors from wire.go:

func InitService(ctx context.Context) (*Service, error) {
	awsConfigManagerImpl := appconfig.NewAwsConfigManager()
	config, err := importerconfig.NewConfig(ctx, awsConfigManagerImpl)
	if err != nil {
		return nil, err
	}
	serviceConfig := NewServiceConfig(config)
	realTimeSource := clock.NewRealTimeSource()
	common := config.Common
	loggingConfig := common.Logging
	logger := logging.DefaultLogger(loggingConfig)
	dynamoDBEventRepositoryConfig := NewDynamoDBEventRepositoryConfig(config)
	dbConfig := common.DynamoDB
	awsConfig := appconfig.AwsConfigProvider(awsConfigManagerImpl)
	client, err := db.NewClient(ctx, dbConfig, awsConfig, logger)
	if err != nil {
		return nil, err
	}
	dynamoDBEventRepository := NewDynamoDBEventRepository(dynamoDBEventRepositoryConfig, client, realTimeSource, logger)
	lambdaProxyGraphQLHandlerConfig := NewLambdaProxyGraphQLHandlerConfig(config)
	lambdaProxyGraphQLHandler := NewLambdaProxyGraphQLHandler(lambdaProxyGraphQLHandlerConfig, logger)
	graphQLMeetupRepository := NewGraphQLMeetupRepository(lambdaProxyGraphQLHandler, logger)
	service := NewService(serviceConfig, realTimeSource, logger, dynamoDBEventRepository, graphQLMeetupRepository)
	return service, nil
}

// wire.go:

var CommonProviders = wire.NewSet(importerconfig.ConfigProviders, logging.DefaultLogger, clock.RealClockProvider, httpclient.DefaultClient, db.Providers)
