// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package syncdynamodb

import (
	"context"
	"github.com/google/wire"
	"sgf-meetup-api/pkg/shared/db"
	"sgf-meetup-api/pkg/shared/logging"
)

// Injectors from wire.go:

func InitService(ctx context.Context, config *Config) (*Service, error) {
	dbConfig := getDbConfig(config)
	loggingConfig := getLoggingConfig(config)
	logger := logging.DefaultLogger(loggingConfig)
	client, err := db.NewClient(ctx, dbConfig, logger)
	if err != nil {
		return nil, err
	}
	service := NewService(client, logger)
	return service, nil
}

// wire.go:

var CommonSet = wire.NewSet(logging.DefaultLogger, getLoggingConfig)

var DBSet = wire.NewSet(getDbConfig, db.NewClient)
