// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package syncdynamodb

import (
	"context"
	"github.com/google/wire"
	"sgf-meetup-api/pkg/shared/db"
	"sgf-meetup-api/pkg/shared/logging"
	"sgf-meetup-api/pkg/syncdynamodb/syncdynamodbconfig"
)

// Injectors from wire.go:

func InitService(ctx context.Context) (*Service, error) {
	config, err := syncdynamodbconfig.NewConfig()
	if err != nil {
		return nil, err
	}
	dbConfig := syncdynamodbconfig.NewDBConfig(config)
	loggingConfig := syncdynamodbconfig.NewLoggingConfig(config)
	logger := logging.DefaultLogger(loggingConfig)
	client, err := db.NewClient(ctx, dbConfig, logger)
	if err != nil {
		return nil, err
	}
	service := NewService(client, logger)
	return service, nil
}

// wire.go:

var CommonSet = wire.NewSet(syncdynamodbconfig.NewConfig, logging.DefaultLogger, syncdynamodbconfig.NewLoggingConfig)

var DBSet = wire.NewSet(syncdynamodbconfig.NewDBConfig, db.NewClient)
