version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      gomod-deps:
        patterns: ["*"]
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-deps:
        patterns: ["*"]
  - package-ecosystem: docker
    directory: /pkg/infra
    schedule:
      interval: weekly
    groups:
      docker-deps:
        patterns: [ "*" ]
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    groups:
      docker-deps:
        patterns: [ "*" ]
