# From https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html
services:
  dynamodb-local:
    image: 'amazon/dynamodb-local:2.6.1'
    ports:
      - '${DYNAMODB_PORT:-8000}:8000'
    working_dir: '/home/dynamodblocal'
    user: root
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    volumes:
      - 'dynamodb:/home/dynamodblocal/data'
    networks:
      - sgf-meetup-api

volumes:
  dynamodb:

networks:
  sgf-meetup-api:
    name: sgf-meetup-api
