definitions:
  apierrors.ProblemDetails:
    properties:
      detail:
        type: string
      instance:
        type: string
      status:
        type: integer
      title:
        type: string
      type:
        type: string
    type: object
  auth.authRequestDTO:
    properties:
      clientId:
        type: string
      clientSecret:
        type: string
    type: object
  auth.authResponseDTO:
    properties:
      accessToken:
        type: string
      accessTokenExpiresAt:
        type: string
      refreshToken:
        type: string
      refreshTokenExpiresAt:
        type: string
    type: object
  auth.refreshTokenRequestDTO:
    properties:
      refreshToken:
        type: string
    type: object
info:
  contact: {}
  title: SGF Meetup API
  version: "1.0"
paths:
  /v1/auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: Credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.authRequestDTO'
      produces:
      - application/json
      - application/problem+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.authResponseDTO'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/apierrors.ProblemDetails'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ProblemDetails'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/apierrors.ProblemDetails'
      summary: Authenticate with credentials
      tags:
      - auth
  /v1/auth/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.refreshTokenRequestDTO'
      produces:
      - application/json
      - application/problem+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.authResponseDTO'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/apierrors.ProblemDetails'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apierrors.ProblemDetails'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/apierrors.ProblemDetails'
      summary: Refresh token
      tags:
      - auth
swagger: "2.0"
