// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"context"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"sgf-meetup-api/pkg/api/auth"
	"sgf-meetup-api/pkg/api/groupevents"
	"sgf-meetup-api/pkg/shared/db"
	"sgf-meetup-api/pkg/shared/logging"
)

import (
	_ "sgf-meetup-api/pkg/api/docs"
)

// Injectors from wire.go:

func InitRouter(ctx context.Context) (*gin.Engine, error) {
	config, err := NewConfig()
	if err != nil {
		return nil, err
	}
	dbConfig := getDbConfig(config)
	loggingConfig := getLoggingConfig(config)
	logger := logging.DefaultLogger(loggingConfig)
	client, err := db.NewClient(ctx, dbConfig, logger)
	if err != nil {
		return nil, err
	}
	service := auth.NewService(client)
	controller := auth.NewController(service)
	groupeventsController := groupevents.NewController()
	engine := NewRouter(controller, groupeventsController)
	return engine, nil
}

// wire.go:

var CommonSet = wire.NewSet(NewConfig, logging.DefaultLogger, getLoggingConfig)

var DbSet = wire.NewSet(getDbConfig, db.NewClient)
