// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package meetupproxy

import (
	"github.com/google/wire"
	"sgf-meetup-api/pkg/shared/clock"
	"sgf-meetup-api/pkg/shared/httpclient"
	"sgf-meetup-api/pkg/shared/logging"
)

// Injectors from wire.go:

func InitService(config *Config) *Service {
	serviceConfig := NewServiceConfig(config)
	realTimeSource := clock.NewRealTimeSource()
	loggingConfig := getLoggingConfig(config)
	logger := logging.DefaultLogger(loggingConfig)
	client := httpclient.DefaultClient(realTimeSource, logger)
	meetupHttpAuthHandlerConfig := NewMeetupAuthHandlerConfig(config)
	meetupHttpAuthHandler := NewMeetupHttpAuthHandler(meetupHttpAuthHandlerConfig, client, logger)
	service := NewService(serviceConfig, client, meetupHttpAuthHandler, logger)
	return service
}

// wire.go:

var CommonSet = wire.NewSet(logging.DefaultLogger, clock.RealClockSet, httpclient.DefaultClient, getLoggingConfig)

var AuthHandlerSet = wire.NewSet(wire.Bind(new(AuthHandler), new(*MeetupHttpAuthHandler)), NewMeetupAuthHandlerConfig, NewMeetupHttpAuthHandler)
