// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package meetupproxy

import (
	"github.com/google/wire"
	"sgf-meetup-api/pkg/shared/clock"
	"sgf-meetup-api/pkg/shared/httpclient"
	"sgf-meetup-api/pkg/shared/logging"
)

// Injectors from wire.go:

func InitService(config *Config) *Service {
	serviceConfig := NewServiceConfig(config)
	timeSource := clock.RealTimeSource()
	loggingConfig := getLoggingConfig(config)
	logger := logging.DefaultLogger(loggingConfig)
	client := httpclient.DefaultClient(timeSource, logger)
	authHandlerConfig := NewAuthHandlerConfig(config)
	meetupproxyAuthHandler := NewAuthHandler(authHandlerConfig, client, logger)
	service := NewService(serviceConfig, client, meetupproxyAuthHandler, logger)
	return service
}

// wire.go:

var CommonSet = wire.NewSet(logging.DefaultLogger, clock.RealTimeSource, httpclient.DefaultClient, getLoggingConfig)
