// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package meetupproxy

import (
	"github.com/google/wire"
	"sgf-meetup-api/pkg/meetupproxy/meetupproxyconfig"
	"sgf-meetup-api/pkg/shared/clock"
	"sgf-meetup-api/pkg/shared/httpclient"
	"sgf-meetup-api/pkg/shared/logging"
)

// Injectors from wire.go:

func InitService() (*Service, error) {
	config, err := meetupproxyconfig.NewConfig()
	if err != nil {
		return nil, err
	}
	serviceConfig := NewServiceConfig(config)
	realTimeSource := clock.NewRealTimeSource()
	loggingConfig := meetupproxyconfig.NewLoggingConfig(config)
	logger := logging.DefaultLogger(loggingConfig)
	client := httpclient.DefaultClient(realTimeSource, logger)
	meetupHttpAuthHandlerConfig := NewMeetupAuthHandlerConfig(config)
	meetupHttpAuthHandler := NewMeetupHttpAuthHandler(meetupHttpAuthHandlerConfig, client, logger)
	service := NewService(serviceConfig, client, meetupHttpAuthHandler, logger)
	return service, nil
}

// wire.go:

var CommonSet = wire.NewSet(meetupproxyconfig.NewConfig, logging.DefaultLogger, clock.RealClockSet, httpclient.DefaultClient, meetupproxyconfig.NewLoggingConfig)

var AuthHandlerSet = wire.NewSet(wire.Bind(new(AuthHandler), new(*MeetupHttpAuthHandler)), NewMeetupAuthHandlerConfig, NewMeetupHttpAuthHandler)
