// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package upsertuser

import (
	"context"
	"sgf-meetup-api/pkg/shared/appconfig"
	"sgf-meetup-api/pkg/shared/db"
	"sgf-meetup-api/pkg/shared/logging"
	"sgf-meetup-api/pkg/upsertuser/upsertuserconfig"
)

// Injectors from wire.go:

func InitService(ctx context.Context) (*Service, error) {
	awsConfigManagerImpl := appconfig.NewAwsConfigManager()
	config, err := upsertuserconfig.NewConfig(ctx, awsConfigManagerImpl)
	if err != nil {
		return nil, err
	}
	common := config.Common
	dbConfig := common.DynamoDB
	awsConfig := appconfig.AwsConfigProvider(awsConfigManagerImpl)
	loggingConfig := common.Logging
	logger := logging.DefaultLogger(ctx, loggingConfig)
	client, err := db.NewClient(ctx, dbConfig, awsConfig, logger)
	if err != nil {
		return nil, err
	}
	service := NewService(config, client)
	return service, nil
}
