name: "Lint PR"
on:
    pull_request:
        branches:
            - main
jobs:
    lint-typecheck:
        name: Lint & Typecheck PR
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.18.0
            - run: npm ci
            - name: 'CDK Synth'
              run: npm run synth
            - name: 'Lint'
              run: npm run lint
            - name: 'Typecheck'
              run: npm run build
