name: "Lint PR"
on:
    pull_request:
        branches:
            - main
jobs:
    lint-typecheck:
        name: Lint & Typecheck PR
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-go@v5
            with:
              go-version: 1.24
          - name: golangci-lint
            uses: golangci/golangci-lint-action@v6
            with:
              version: v1.64
              args: cmd/... pkg/...
